-- Separate schema: does not alter the tables of the previous dashboard.
CREATE SCHEMA IF NOT EXISTS ppcm;
CREATE TABLE IF NOT EXISTS ppcm.imports (
  id uuid PRIMARY KEY, type text NOT NULL CHECK(type IN ('notice','order')),
  filename text NOT NULL, imported_at timestamptz NOT NULL DEFAULT now(),
  row_count integer NOT NULL, metadata jsonb NOT NULL, records jsonb NOT NULL
);
CREATE TABLE IF NOT EXISTS ppcm.sources (
  type text PRIMARY KEY CHECK(type IN ('notice','order')), import_id uuid NOT NULL REFERENCES ppcm.imports(id)
);
CREATE TABLE IF NOT EXISTS ppcm.followups (
  key text PRIMARY KEY, payload jsonb NOT NULL, version integer NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS ppcm.activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, record_key text NOT NULL,
  at timestamptz NOT NULL DEFAULT now(), detail jsonb NOT NULL
);
CREATE INDEX IF NOT EXISTS ppcm_activity_record_idx ON ppcm.activity(record_key,id DESC);
CREATE TABLE IF NOT EXISTS ppcm.settings (id integer PRIMARY KEY CHECK(id=1), payload jsonb NOT NULL);
INSERT INTO ppcm.settings VALUES (1, '{"currency":"","workspaceName":"Operaciones forestales"}') ON CONFLICT DO NOTHING;
CREATE TABLE IF NOT EXISTS ppcm.members (
  id uuid PRIMARY KEY, auth_user_id uuid UNIQUE, email text UNIQUE NOT NULL,
  display_name text NOT NULL, role text NOT NULL CHECK(role IN ('admin','editor','viewer')),
  active boolean NOT NULL DEFAULT true, created_at timestamptz NOT NULL DEFAULT now()
);
-- Only the server's PostgreSQL connection can access these tables. The schema
-- is not exposed through the public Data API; no browser service key is needed.
REVOKE ALL ON SCHEMA ppcm FROM PUBLIC;
REVOKE ALL ON ALL TABLES IN SCHEMA ppcm FROM PUBLIC;
ALTER TABLE ppcm.imports ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppcm.sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppcm.followups ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppcm.activity ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppcm.settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE ppcm.members ENABLE ROW LEVEL SECURITY;
