module.exports = {
  appId: "cl.ppcm.mantenimiento",
  productName: "PPCM Mantenimiento",
  directories: { output: "release", buildResources: "build" },
  files: [
    "main.cjs",
    "preload.cjs",
    "connection.cjs",
    "setup.html",
    "setup.js",
    "setup.css",
    "default-server.json",
    "build/icon.png",
    "package.json",
  ],
  asar: true,
  win: {
    target: [{ target: "nsis", arch: ["x64"] }],
    icon: "build/icon.ico",
    signAndEditExecutable: true,
    signExecutable: Boolean(process.env.CSC_LINK),
  },
  nsis: {
    oneClick: false,
    perMachine: false,
    allowElevation: false,
    allowToChangeInstallationDirectory: true,
    createDesktopShortcut: "always",
    createStartMenuShortcut: true,
    shortcutName: "PPCM Mantenimiento",
    installerIcon: "build/icon.ico",
    uninstallerIcon: "build/icon.ico",
    deleteAppDataOnUninstall: false,
    artifactName: "PPCM-Setup-${version}-${arch}.${ext}",
    language: "3082",
  },
};
